### 1. 新しい目標を作成する (POST)
POST http://localhost:8080/api/goals
Authorization: 4e9de250-bc82-49bd-ae2b-ea4d7183c3f9
Content-Type: application/json

{
  "title": "ぴょんすけ",
  "targetDate": "2027-05-19",
  "startDate": "2026-07-28"
}

### 2. 目標の一覧を取得する (GET) ?userId=でユーザーして取得
GET http://localhost:8080/api/goals?userId=4
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee

### DELETE目標の削除
DELETE http://localhost:8080/api/goals/20
Authorization: 4e9de250-bc82-49bd-ae2b-ea4d7183c3f9

### 目標の更新
PUT http://localhost:8080/api/goals/14
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee
Content-Type: application/json

{
  "title": "江南スタイル",
  "targetDate": "2026-10-31",
  "startDate": "2026-09-28"
}


### 3. 新しい「✕」を書く（POST)
POST http://localhost:8080/api/goals/14/marks
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee
Content-Type: application/json

{
  "markedDate": "2026-09-28"
}

### 4. goalIdの「✕」マーク書かれた日一覧を取得（GET)
GET http://localhost:8080/api/goals/14
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee

### 4. 「✕」マーク書かれた日一覧を取得（GET)
GET http://localhost:8080/api/goals/14/marks
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee

### 全ユーザー取得
GET http://localhost:8080/api/users

### ユーザーの登録
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "武士"
}

### ユーザーの削除
DELETE http://localhost:8080/api/users/6

### 目標の削除（正しいトークンの場合）
DELETE http://localhost:8080/api/goals/16
Authorization: d10ab66a-0191-4099-9413-a30dadfbe2ee


### 目標の削除（他人のトークン、または適当な文字列の場合）
DELETE http://localhost:8080/api/goals/14
Authorization: dammy-token-12345