### 1. 新しい目標を作成する (POST)
POST http://localhost:8080/api/goals
Content-Type: application/json

{
  "title": "志望校合格",
  "targetDate": "2026-12-31",
  "startDate": "2026-08-28"
}

### 2. 目標の一覧を取得する (GET)
GET http://localhost:8080/api/goals


### 3. 新しい「✕」を書く（POST)
POST http://localhost:8080/api/goals/4/marks
Content-Type: application/json

{
  "markedDate": "2026-11-14"
}

### 4. 「✕」マーク書かれた日一覧を取得（GET)
GET http://localhost:8080/api/goals/1/marks