spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/goal_app
spring.datasource.username=root
spring.datasource.password=nB3&5LU&pbfz

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG